### PR TITLE
ci: Automate the release process

### LINKED ISSUE #273: Automatically generate changelog from the commit messages
Same as we do in Crawlee, see https://github.com/apify/crawlee-python/issues/18.

### PR DESCRIPTION
**Pull request by janbuchar**
- closes #273

### CODE REVIEW

**Review by vdusek — CHANGES_REQUESTED** [review]
Great, but please update also:
- `.pre-commit-config.yaml` - rm legacy checks,
- `Makefile` - rm legacy commands,
- and `CONTRIBUTING.md` - basically just copy it from Crawlee and make necessary adjustments.

**Review by vdusek — CHANGES_REQUESTED** [review]
All our pipeline files so far follow a verb-based naming style (`build_and_deploy_docs.yaml`, `check_pr_title.yaml`, `run_code_checks.yaml`, `update_new_issue.yaml`). The release pipelines, however, are named `release` and `pre_release`. While I'm not insisting we have to use verb-style naming—I'm not sure what the best convention is—but please keep it consistent.

**Comment by janbuchar** [comment]
> All our pipeline files so far follow a verb-based naming style (`build_and_deploy_docs.yaml`, `check_pr_title.yaml`, `run_code_checks.yaml`, `update_new_issue.yaml`). The release pipelines, however, are named `release` and `pre_release`. While I'm not insisting we have to use verb-style naming—I'm not sure what the best convention is—but please keep it consistent.

Release can be a verb, and I'd argue that the same holds for pre-release. As long as people know what to expect to find in those files (please tell me if that isn't the case), I wouldn't waste time on contemplating better names.

**Review by vdusek — APPROVED** [review]
Great job! Thanks

**Pull request merged**
